### ISSUE TITLE
Don't wipe out memory of lstm before sending state to the decoder 

### ISSUE THREAD

**Issue by vseledkin** [vivanov879/translator#1]
According to my experience it is useful for decoder. 
And how can i contact you i am working on very the same model it will be useful to discuss, my Skype name "seledkin"

**Comment by vivanov879** [comment]
+7 985 915 64 87
vivanov879@ya.ru

**Comment by vivanov879** [comment]
im running the model right now for several days -- the results not satisfactory

**Comment by vivanov879** [comment]
i want to increase number of layers to 4 and rnn_size to 2000 and run it on amazon ec2 -- will be much better i guess

**Comment by vivanov879** [comment]
ill contact you on weekend -- im on a trip right now

**Comment by vivanov879** [comment]
i didnt see where i erase memory -- can you maybe point to a line in code ?

**Comment by vivanov879** [comment]
do you mean that lstm_c_dec is set to zeros evey run ? 

## https://github.com/vivanov879/translator/blob/master/train_multi_layer_cuda.lua#L150

lstm_h_dec is set to to lstm_h_enc https://github.com/vivanov879/translator/blob/master/train_multi_layer_cuda.lua#L151

**Comment by vivanov879** [comment]
it doesnt wipe memory any more -- changed like you said

**Comment by vseledkin** [comment]
yes exactly.  Yesterday i got my version working (i guess) i cannot share my implementation because working on private company. Do you see your version is able to remember small dataset. Mine is very easy to overfit on small data (200 sentences) and on very small 16 cell 1 layer lstm and this is good sign.

If you don't see it working on small data when your implementation is incorrect

I want to ask you to share your corpora so i can run and test your version

**Comment by vseledkin** [comment]
also wiping here https://github.com/vivanov879/translator/blob/master/train.lua#L163

**Comment by vivanov879** [comment]
im using yandex corpus from WMT workshop. https://translate.yandex.ru/corpus?lang=ru . fill in the blanks and tell them you are a wmt workshop participant and they'll send you

**Comment by vivanov879** [comment]
i made changes to train_multi_layer_cuda.lua

**Comment by ffmpbgrnn** [comment]
Hi @vivanov879 ! I'm very interested in this work and I'm curious how's the performance now?

**Comment by vivanov879** [comment]
still looking to run it on ec2 -- it does train well on around 100 sentences in several minutes, so it need more extensive training

24.07.2015, 03:45, "Linchao Zhu" notifications@github.com:

**Comment by ffmpbgrnn** [comment]
I am trying to run seq2seq on video tasks. Than would be very large data.

**Comment by vivanov879** [comment]
as soon as i run larger tests i will inform you about results
so far you can run train_multi_layer_cuda_batch.lua script to see it run on small dataset

**Comment by ffmpbgrnn** [comment]
Yes. I will try some datasets!
